export const AuthCMD = {
    REGISTER:'REGISTER',
    LOGIN: 'LOGIN',
    GET_REFRESH_TOKEN: 'GET_REFRESH_TOKEN',
    VERIFY_JWT: 'VERIFY_JWT',
}

export const UserCMD = {
    CREATE:'CREATE',
    UPDATE:'UPDATE',
    DELETE:'DELETE',
    GET:'GET',
    GET_PROFILE:'GET_PROFILE',
    CHANGE_PROFILE:'CHANGE_PROFILE',
    GET_ALL:'GET_ALL',
    CHANGE_PASSWORD:'CHANGE_PASSWORD',
}